const std = @import("std");

pub const Gauge = struct {
    allocator: std.mem.Allocator,
    io: std.Io,
    name: []u8,
    help: []u8,
    label_names: [][]u8,
    mutex: std.Io.Mutex = .init,
    series: std.ArrayList(Series) = .empty,

    const Series = struct {
        label_values: [][]u8,
        value: f64,
    };

    fn create(allocator: std.mem.Allocator, io: std.Io, name: []const u8, label_names: []const []const u8) !*Gauge {
        const gauge = try allocator.create(Gauge);
        errdefer allocator.destroy(gauge);
        const owned_name = try allocator.dupe(u8, name);
        errdefer allocator.free(owned_name);
        const help = try std.fmt.allocPrint(allocator, "{s} generated by json2prom", .{name});
        errdefer allocator.free(help);
        gauge.* = .{
            .allocator = allocator,
            .io = io,
            .name = owned_name,
            .help = help,
            .label_names = try dupeStrings(allocator, label_names),
        };
        return gauge;
    }

    fn destroy(self: *Gauge) void {
        const allocator = self.allocator;
        self.clearSeries();
        self.series.deinit(allocator);
        freeStrings(allocator, self.label_names);
        allocator.free(self.name);
        allocator.free(self.help);
        allocator.destroy(self);
    }

    /// Removes every series written by previous scrapes.
    pub fn reset(self: *Gauge) void {
        self.mutex.lockUncancelable(self.io);
        defer self.mutex.unlock(self.io);
        self.clearSeries();
    }

    pub fn set(self: *Gauge, label_values: []const []const u8, value: f64) !void {
        std.debug.assert(label_values.len == self.label_names.len);
        self.mutex.lockUncancelable(self.io);
        defer self.mutex.unlock(self.io);

        for (self.series.items) |*series| {
            if (labelValuesEqual(series.label_values, label_values)) {
                series.value = value;
                return;
            }
        }
        const owned = try dupeStrings(self.allocator, label_values);
        errdefer freeStrings(self.allocator, owned);
        try self.series.append(self.allocator, .{ .label_values = owned, .value = value });
    }

    fn clearSeries(self: *Gauge) void {
        for (self.series.items) |series| {
            freeStrings(self.allocator, series.label_values);
        }
        self.series.clearRetainingCapacity();
    }

    fn write(self: *Gauge, w: *std.Io.Writer) !void {
        self.mutex.lockUncancelable(self.io);
        defer self.mutex.unlock(self.io);

        try w.print("# HELP {s} {s}\n", .{ self.name, self.help });
        try w.print("# TYPE {s} gauge\n", .{self.name});
        for (self.series.items) |series| {
            try w.writeAll(self.name);
            if (self.label_names.len > 0) {
                try w.writeByte('{');
                for (self.label_names, series.label_values, 0..) |label_name, label_value, i| {
                    if (i > 0) try w.writeByte(',');
                    try w.print("{s}=\"", .{label_name});
                    try writeEscaped(w, label_value);
                    try w.writeByte('"');
                }
                try w.writeByte('}');
            }
            try w.print(" {d}\n", .{series.value});
        }
    }
};

fn writeEscaped(w: *std.Io.Writer, value: []const u8) !void {
    for (value) |byte| switch (byte) {
        '\\' => try w.writeAll("\\\\"),
        '"' => try w.writeAll("\\\""),
        '\n' => try w.writeAll("\\n"),
        else => try w.writeByte(byte),
    };
}

fn labelValuesEqual(a: []const []const u8, b: []const []const u8) bool {
    for (a, b) |x, y| {
        if (!std.mem.eql(u8, x, y)) return false;
    }
    return true;
}

fn dupeStrings(allocator: std.mem.Allocator, strings: []const []const u8) ![][]u8 {
    const owned = try allocator.alloc([]u8, strings.len);
    var done: usize = 0;
    errdefer {
        for (owned[0..done]) |s| allocator.free(s);
        allocator.free(owned);
    }
    for (strings, 0..) |s, i| {
        owned[i] = try allocator.dupe(u8, s);
        done += 1;
    }
    return owned;
}

fn freeStrings(allocator: std.mem.Allocator, strings: [][]u8) void {
    for (strings) |s| allocator.free(s);
    allocator.free(strings);
}

pub const Registry = struct {
    allocator: std.mem.Allocator,
    io: std.Io,
    mutex: std.Io.Mutex = .init,
    gauges: std.ArrayList(*Gauge) = .empty,

    pub fn init(allocator: std.mem.Allocator, io: std.Io) Registry {
        return .{ .allocator = allocator, .io = io };
    }

    pub fn deinit(self: *Registry) void {
        for (self.gauges.items) |g| g.destroy();
        self.gauges.deinit(self.allocator);
    }

    pub fn gauge(self: *Registry, name: []const u8, label_names: []const []const u8) !*Gauge {
        self.mutex.lockUncancelable(self.io);
        defer self.mutex.unlock(self.io);
        const g = try Gauge.create(self.allocator, self.io, name, label_names);
        errdefer g.destroy();
        try self.gauges.append(self.allocator, g);
        return g;
    }

    pub fn render(self: *Registry, w: *std.Io.Writer) !void {
        self.mutex.lockUncancelable(self.io);
        defer self.mutex.unlock(self.io);
        for (self.gauges.items) |g| try g.write(w);
    }

    pub fn renderAlloc(self: *Registry, allocator: std.mem.Allocator) ![]u8 {
        var aw: std.Io.Writer.Allocating = .init(allocator);
        defer aw.deinit();
        try self.render(&aw.writer);
        return aw.toOwnedSlice();
    }
};

test "gauge with target label renders prometheus text" {
    var registry: Registry = .init(std.testing.allocator, std.testing.io);
    defer registry.deinit();

    const g = try registry.gauge("evo_percentage", &.{ "target", "name" });
    try g.set(&.{ "evo-enge", "Enge" }, 42.5);

    const out = try registry.renderAlloc(std.testing.allocator);
    defer std.testing.allocator.free(out);

    try std.testing.expectEqualStrings(
        \\# HELP evo_percentage evo_percentage generated by json2prom
        \\# TYPE evo_percentage gauge
        \\evo_percentage{target="evo-enge",name="Enge"} 42.5
        \\
    , out);
}

test "no labels renders bare metric" {
    var registry: Registry = .init(std.testing.allocator, std.testing.io);
    defer registry.deinit();

    const g = try registry.gauge("simple", &.{});
    try g.set(&.{}, 3);

    const out = try registry.renderAlloc(std.testing.allocator);
    defer std.testing.allocator.free(out);
    try std.testing.expect(std.mem.indexOf(u8, out, "\nsimple 3\n") != null);
}

test "reset removes all series" {
    var registry: Registry = .init(std.testing.allocator, std.testing.io);
    defer registry.deinit();

    const g = try registry.gauge("m", &.{"target"});
    try g.set(&.{"a"}, 1);
    try g.set(&.{"b"}, 2);
    try std.testing.expectEqual(2, g.series.items.len);

    g.reset();
    try std.testing.expectEqual(0, g.series.items.len);

    const out = try registry.renderAlloc(std.testing.allocator);
    defer std.testing.allocator.free(out);
    try std.testing.expectEqualStrings(
        \\# HELP m m generated by json2prom
        \\# TYPE m gauge
        \\
    , out);
}

test "re-scrape replaces series without stale leftovers" {
    var registry: Registry = .init(std.testing.allocator, std.testing.io);
    defer registry.deinit();

    const g = try registry.gauge("m", &.{ "target", "loc" });
    try g.set(&.{ "t", "old-location" }, 1);
    try g.set(&.{ "t", "kept" }, 2);

    g.reset();
    try g.set(&.{ "t", "kept" }, 5);

    const out = try registry.renderAlloc(std.testing.allocator);
    defer std.testing.allocator.free(out);
    try std.testing.expect(std.mem.indexOf(u8, out, "old-location") == null);
    try std.testing.expect(std.mem.indexOf(u8, out, "m{target=\"t\",loc=\"kept\"} 5") != null);
}

test "same label combination overwrites within a scrape" {
    var registry: Registry = .init(std.testing.allocator, std.testing.io);
    defer registry.deinit();

    const g = try registry.gauge("m", &.{"target"});
    try g.set(&.{"t"}, 1);
    try g.set(&.{"t"}, 2);
    try std.testing.expectEqual(1, g.series.items.len);
    try std.testing.expectEqual(2, g.series.items[0].value);
}

test "label values are escaped" {
    var registry: Registry = .init(std.testing.allocator, std.testing.io);
    defer registry.deinit();

    const g = try registry.gauge("m", &.{"target"});
    try g.set(&.{"a\"b\\c\nd"}, 1);

    const out = try registry.renderAlloc(std.testing.allocator);
    defer std.testing.allocator.free(out);
    try std.testing.expect(std.mem.indexOf(u8, out, "m{target=\"a\\\"b\\\\c\\nd\"} 1") != null);
}

test "multiple gauges render in registration order" {
    var registry: Registry = .init(std.testing.allocator, std.testing.io);
    defer registry.deinit();

    _ = try registry.gauge("first", &.{"target"});
    _ = try registry.gauge("second", &.{"target"});

    const out = try registry.renderAlloc(std.testing.allocator);
    defer std.testing.allocator.free(out);
    try std.testing.expect(std.mem.indexOf(u8, out, "first").? < std.mem.indexOf(u8, out, "second").?);
}
