const std = @import("std");
const config = @import("config.zig");
const metrics = @import("metrics.zig");
const poller = @import("poller.zig");
const jq = @import("jq.zig");

const Pipeline = struct {
    cfg: config.Config,
    registry: metrics.Registry,
    compiled: std.ArrayList(poller.CompiledMetric),

    fn init(source: []const u8) !Pipeline {
        var pipeline: Pipeline = .{
            .cfg = try config.parse(std.testing.allocator, source),
            .registry = .init(std.testing.allocator, std.testing.io),
            .compiled = .empty,
        };
        errdefer pipeline.deinit();
        for (pipeline.cfg.targets) |target| {
            for (target.metrics) |mc| {
                const cm = try poller.CompiledMetric.compile(std.testing.allocator, &pipeline.registry, mc);
                try pipeline.compiled.append(std.testing.allocator, cm);
            }
        }
        return pipeline;
    }

    fn deinit(self: *Pipeline) void {
        for (self.compiled.items) |*cm| cm.deinit(std.testing.allocator);
        self.compiled.deinit(std.testing.allocator);
        self.registry.deinit();
        self.cfg.deinit();
    }

    fn evaluateAll(self: *Pipeline, target_name: []const u8, json: []const u8) !void {
        const root = try jq.parseJson(json);
        defer jq.free(root);
        for (self.compiled.items) |*cm| {
            try poller.evaluateMetric(std.testing.allocator, target_name, cm, root);
        }
    }

    fn render(self: *Pipeline) ![]u8 {
        return self.registry.renderAlloc(std.testing.allocator);
    }
};

test "full pipeline: config to prometheus text" {
    var pipeline = try Pipeline.init(
        \\targets:
        \\  - name: evo-enge
        \\    uri: https://example.com/api
        \\    periodSeconds: 60
        \\    metrics:
        \\      - name: evo_percentage
        \\        valueQuery: .percentageUsed
        \\        labels:
        \\          - name: name
        \\            query: .name
        \\          - name: max_capacity
        \\            query: .max_capacity
        \\      - name: evo_capacity
        \\        valueQuery: .current
        \\        labels:
        \\          - name: name
        \\            query: .name
    );
    defer pipeline.deinit();

    try pipeline.evaluateAll("evo-enge",
        \\{"percentageUsed": 53.75, "current": 43, "name": "Enge", "max_capacity": 80}
    );

    const out = try pipeline.render();
    defer std.testing.allocator.free(out);

    try std.testing.expect(std.mem.indexOf(u8, out, "# HELP evo_percentage evo_percentage generated by json2prom") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "# TYPE evo_percentage gauge") != null);
    try std.testing.expect(std.mem.indexOf(u8, out,
        \\evo_percentage{target="evo-enge",name="Enge",max_capacity="80"} 53.75
    ) != null);
    try std.testing.expect(std.mem.indexOf(u8, out,
        \\evo_capacity{target="evo-enge",name="Enge"} 43
    ) != null);
}

test "full pipeline: itemsQuery stream with literal label query" {
    var pipeline = try Pipeline.init(
        \\targets:
        \\  - name: limmat-water-temp
        \\    uri: https://example.com/hydro
        \\    periodSeconds: 300
        \\    metrics:
        \\      - name: river_water_temperature_celsius
        \\        itemsQuery: .payload[]
        \\        valueQuery: .val
        \\        labels:
        \\          - name: location
        \\            query: "\"Limmat-Baden\""
        \\          - name: station_id
        \\            query: .loc
    );
    defer pipeline.deinit();

    try pipeline.evaluateAll("limmat-water-temp",
        \\{"payload": [{"val": 12.3, "loc": 2243}, {"val": 13.1, "loc": 2244}]}
    );

    const out = try pipeline.render();
    defer std.testing.allocator.free(out);

    try std.testing.expect(std.mem.indexOf(u8, out,
        \\river_water_temperature_celsius{target="limmat-water-temp",location="Limmat-Baden",station_id="2243"} 12.3
    ) != null);
    try std.testing.expect(std.mem.indexOf(u8, out,
        \\river_water_temperature_celsius{target="limmat-water-temp",location="Limmat-Baden",station_id="2244"} 13.1
    ) != null);
}

test "full pipeline: second scrape drops stale series" {
    var pipeline = try Pipeline.init(
        \\targets:
        \\  - name: t
        \\    uri: https://example.com
        \\    periodSeconds: 5
        \\    metrics:
        \\      - name: gauge_metric
        \\        itemsQuery: .[]
        \\        valueQuery: .v
        \\        labels:
        \\          - name: id
        \\            query: .id
    );
    defer pipeline.deinit();

    try pipeline.evaluateAll("t",
        \\[{"id": "a", "v": 1}, {"id": "b", "v": 2}]
    );
    try pipeline.evaluateAll("t",
        \\[{"id": "c", "v": 3}]
    );

    const out = try pipeline.render();
    defer std.testing.allocator.free(out);

    try std.testing.expect(std.mem.indexOf(u8, out, "id=\"a\"") == null);
    try std.testing.expect(std.mem.indexOf(u8, out, "id=\"b\"") == null);
    try std.testing.expect(std.mem.indexOf(u8, out, "gauge_metric{target=\"t\",id=\"c\"} 3") != null);
}

test "config file loads through config.load" {
    const source =
        \\targets:
        \\  - name: integration-test
        \\    uri: http://example.com/api
        \\    method: GET
        \\    periodSeconds: 30
        \\    metrics:
        \\      - name: test_gauge
        \\        valueQuery: .value
        \\        labels:
        \\          - name: status
        \\            query: .status
    ;

    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();
    try tmp.dir.writeFile(std.testing.io, .{ .sub_path = "config.yaml", .data = source });

    const path = try tmp.dir.realPathFileAlloc(std.testing.io, "config.yaml", std.testing.allocator);
    defer std.testing.allocator.free(path);

    var cfg = try config.load(std.testing.allocator, std.testing.io, path);
    defer cfg.deinit();

    try std.testing.expectEqual(1, cfg.targets.len);
    try std.testing.expectEqualStrings("integration-test", cfg.targets[0].name);
    try std.testing.expectEqual(30, cfg.targets[0].period_seconds);
    try std.testing.expectEqualStrings(".status", cfg.targets[0].metrics[0].labels[0].query);
}

test "invalid jq query in config fails at startup" {
    try std.testing.expectError(error.CompileError, Pipeline.init(
        \\targets:
        \\  - name: t
        \\    uri: https://example.com
        \\    periodSeconds: 5
        \\    metrics:
        \\      - name: m
        \\        valueQuery: ".broken["
    ));
}
