use crate::config::{Method, Target};
use crate::extract::MetricExtractor;

use anyhow::{Context, Result, bail, ensure};
use prometheus::{GaugeVec, Opts, Registry};
use reqwest::Client;
use std::time::Duration;
use tokio::time;
use tracing::{debug, error, warn};

impl From<Method> for reqwest::Method {
    fn from(method: Method) -> Self {
        match method {
            Method::Get => Self::GET,
            Method::Post => Self::POST,
            Method::Put => Self::PUT,
            Method::Delete => Self::DELETE,
        }
    }
}

struct BoundMetric {
    extractor: MetricExtractor,
    gauge: GaugeVec,
}

pub struct Poller {
    target: Target,
    metrics: Vec<BoundMetric>,
}

impl Poller {
    pub fn new(target: Target, registry: &Registry) -> Result<Self> {
        let metrics = Self::bind_metrics(&target, registry)
            .with_context(|| format!("Failed to create poller for target '{}'", target.name))?;
        Ok(Poller { target, metrics })
    }

    fn bind_metrics(target: &Target, registry: &Registry) -> Result<Vec<BoundMetric>> {
        if let Some(token_env) = &target.use_bearer_token_from
            && std::env::var(token_env).unwrap_or_default().is_empty()
        {
            bail!("bearer token environment variable '{token_env}' is not set or empty");
        }

        let mut metrics = Vec::with_capacity(target.metrics.len());
        for def in &target.metrics {
            let extractor =
                MetricExtractor::compile(def).with_context(|| format!("metric '{}'", def.name))?;

            let mut label_names = vec!["target"];
            label_names.extend(def.labels.iter().flatten().map(|l| l.name.as_str()));
            let opts = Opts::new(&def.name, format!("{} generated by json2prom", def.name));
            let gauge = GaugeVec::new(opts, &label_names)
                .with_context(|| format!("failed to create gauge for metric '{}'", def.name))?;
            registry
                .register(Box::new(gauge.clone()))
                .with_context(|| format!("failed to register metric '{}'", def.name))?;

            metrics.push(BoundMetric { extractor, gauge });
        }
        Ok(metrics)
    }

    pub async fn run(self, client: Client) {
        let mut interval = time::interval(Duration::from_secs(self.target.period_seconds));
        loop {
            interval.tick().await;
            match self.scrape(&client).await {
                Ok(body) => self.update(&body),
                Err(e) => error!("scrape of '{}' failed: {e:#}", self.target.name),
            }
        }
    }

    async fn scrape(&self, client: &Client) -> Result<String> {
        debug!("sending request to {}", self.target.uri);
        let mut req = client.request(self.target.method.into(), &self.target.uri);

        if let Some(token_env) = &self.target.use_bearer_token_from {
            let token = std::env::var(token_env)
                .with_context(|| format!("bearer token environment variable '{token_env}'"))?;
            req = req.bearer_auth(token);
        }
        for (k, v) in self.target.headers.iter().flatten() {
            req = req.header(k.as_str(), v.as_str());
        }
        if let Some(params) = &self.target.form_params {
            req = req.form(params);
        }

        let resp = req.send().await?;
        ensure!(resp.status().is_success(), "HTTP status {}", resp.status());
        Ok(resp.text().await?)
    }

    pub fn update(&self, body: &str) {
        let root = match jaq_json::read::parse_single(body.as_bytes()) {
            Ok(val) => val,
            Err(e) => {
                warn!("failed to parse JSON from '{}': {e}", self.target.name);
                return;
            }
        };
        for metric in &self.metrics {
            metric.gauge.reset();
            for (labels, value) in metric.extractor.extract(&root) {
                let mut values = Vec::with_capacity(labels.len() + 1);
                values.push(self.target.name.as_str());
                values.extend(labels.iter().map(String::as_str));
                metric.gauge.with_label_values(&values).set(value);
            }
        }
    }
}
