targets:
  - name: splunk-mastermind-logs-to-metrics
    uri: https://host_asdasd:8080/adasda/asdasd/asdasd
    method: POST
    includeAuthHeader: "true"
    headers:
      Content-Type: application/x-www-form-urlencoded
    formParams:
      param1: value1
      param2: value2
    periodSeconds: 60
    metrics:
      - name: kafka_connectors_state
        itemsQuery: .answers
        valueQuery: .connector.status == "READY" | if . then 1 else 0 end
        labels:
          - name: status
            query: .connector.sttaus
          - name: name
            query: .connector.name
  - name: kafka-connector-staus
    uri: https://host_asdasd:8080/adasda/asdasd/asdasd
    method: GET
    periodSeconds: 15
    metrics:
      - name: kafka_connectors_state
    itemsQuery: .answers
    valueQuery: .connector.status == "READY" | if . then 1 else 0 end
    labels:
      - name: status
        query: .connector.sttaus
      - name: name
        query: .connector.name
