global:
  scrape_interval: 30s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  # - "rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "json2prom"
    static_configs:
      - targets: ["json2prom:9100"]
    metrics_path: "/metrics"
    scrape_interval: 30s
