package main

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log/slog"
	"math/big"
	"net/http"
	"net/url"
	"os"
	"strings"
	"time"

	"github.com/itchyny/gojq"
	"github.com/prometheus/client_golang/prometheus"
)

type Poller struct {
	tgt     Target
	client  *http.Client
	metrics []*metricBinding
	logger  *slog.Logger
}

type metricBinding struct {
	itemsQuery   *gojq.Query
	valueQuery   *gojq.Query
	labelQueries []*gojq.Query
	gauge        *prometheus.GaugeVec
}

func NewPoller(tgt Target, reg prometheus.Registerer, logger *slog.Logger) (*Poller, error) {
	p := &Poller{
		tgt:    tgt,
		client: &http.Client{Timeout: 10 * time.Second},
		logger: logger.With("target", tgt.Name),
	}
	for _, m := range tgt.Metrics {
		mb, err := prepareMetric(m, reg)
		if err != nil {
			return nil, fmt.Errorf("metric %s: %w", m.Name, err)
		}
		p.metrics = append(p.metrics, mb)
	}
	return p, nil
}

func prepareMetric(mc MetricConfig, reg prometheus.Registerer) (*metricBinding, error) {
	itemsQ, err := gojq.Parse(mc.ItemsQuery)
	if err != nil {
		return nil, fmt.Errorf("itemsQuery parse: %w", err)
	}
	valueQ, err := gojq.Parse(mc.ValueQuery)
	if err != nil {
		return nil, fmt.Errorf("valueQuery parse: %w", err)
	}

	labelNames := []string{"target"}
	var labelQueries []*gojq.Query
	for _, l := range mc.Labels {
		q, err := gojq.Parse(l.Query)
		if err != nil {
			return nil, fmt.Errorf("label %s query parse: %w", l.Name, err)
		}
		labelNames = append(labelNames, l.Name)
		labelQueries = append(labelQueries, q)
	}

	g := prometheus.NewGaugeVec(prometheus.GaugeOpts{
		Name: mc.Name,
		Help: mc.Name + " generated by json2prom",
	}, labelNames)
	if err := reg.Register(g); err != nil {
		return nil, err
	}

	return &metricBinding{
		itemsQuery:   itemsQ,
		valueQuery:   valueQ,
		labelQueries: labelQueries,
		gauge:        g,
	}, nil
}

func (p *Poller) Run(ctx context.Context) {
	ticker := time.NewTicker(time.Duration(p.tgt.PeriodSeconds) * time.Second)
	defer ticker.Stop()

	p.scrapeOnce(ctx)
	for {
		select {
		case <-ticker.C:
			p.scrapeOnce(ctx)
		case <-ctx.Done():
			return
		}
	}
}

func (p *Poller) scrapeOnce(ctx context.Context) {
	p.logger.Debug("polling target", "url", p.tgt.URI)
	req, err := p.buildRequest(ctx)
	if err != nil {
		p.logger.Error("build request failed", "error", err)
		return
	}
	resp, err := p.client.Do(req)
	if err != nil {
		p.logger.Error("http error", "error", err)
		return
	}
	defer resp.Body.Close()

	if resp.StatusCode/100 != 2 {
		p.logger.Warn("non-2xx status", "status", resp.StatusCode)
		return
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		p.logger.Error("read body", "error", err)
		return
	}

	var root any
	if err := json.Unmarshal(body, &root); err != nil {
		p.logger.Error("json decode", "error", err)
		return
	}

	p.evaluate(root)
}

func (p *Poller) buildRequest(ctx context.Context) (*http.Request, error) {
	var body io.Reader
	if len(p.tgt.FormParams) > 0 {
		vals := url.Values{}
		for k, v := range p.tgt.FormParams {
			vals.Set(k, v)
		}
		body = strings.NewReader(vals.Encode())
	}

	req, err := http.NewRequestWithContext(ctx, p.tgt.Method, p.tgt.URI, body)
	if err != nil {
		return nil, err
	}
	if body != nil {
		req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	}
	for k, v := range p.tgt.Headers {
		req.Header.Set(k, v)
	}
	if p.tgt.UseBearerTokenFrom != "" {
		req.Header.Set("Authorization", "Bearer "+os.Getenv(p.tgt.UseBearerTokenFrom))
	}
	return req, nil
}

func (p *Poller) evaluate(root any) {
	for _, mb := range p.metrics {
		mb.gauge.Reset()

		iter := mb.itemsQuery.Run(root)
		for {
			item, ok := iter.Next()
			if !ok {
				break
			}
			if err, ok := item.(error); ok {
				p.logger.Error("itemsQuery error", "error", err)
				continue
			}

			raw, _ := mb.valueQuery.Run(item).Next()
			num, ok := toFloat64(raw)
			if !ok {
				p.logger.Warn("non-numeric value, skipping item", "value", raw)
				continue
			}

			labelVals := make([]string, 0, len(mb.labelQueries)+1)
			labelVals = append(labelVals, p.tgt.Name)
			for _, q := range mb.labelQueries {
				lv, ok := q.Run(item).Next()
				if !ok {
					lv = nil
				}
				labelVals = append(labelVals, labelValue(lv))
			}
			mb.gauge.WithLabelValues(labelVals...).Set(num)
		}
	}
}

func toFloat64(v any) (float64, bool) {
	switch t := v.(type) {
	case float64:
		return t, true
	case int:
		return float64(t), true
	case *big.Int:
		f, _ := new(big.Float).SetInt(t).Float64()
		return f, true
	case bool:
		if t {
			return 1, true
		}
		return 0, true
	default:
		return 0, false
	}
}

func labelValue(v any) string {
	switch t := v.(type) {
	case nil:
		return ""
	case string:
		return t
	case error:
		return ""
	default:
		b, err := json.Marshal(t)
		if err != nil {
			return fmt.Sprint(t)
		}
		return string(b)
	}
}
