name: Go
on:
  push:
    branches: ["main"]
    paths:
      - "go/**"
  pull_request:
    branches: ["main"]
    paths:
      - "go/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./go
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go/go.mod"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
